export { default as Service } from './Service'
export { default as AccessDenied } from './AccessDenied'
export { default as GDPRPage } from './GDPRPage'
export { default as NotFound } from './NotFound'
export { default as TermsAndConditionsOfUse } from './TermsAndConditionsOfUse'
